# Generated by Django 5.2.7 on 2025-10-13 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contestant',
            old_name='name',
            new_name='name_or_group_name',
        ),
    ]
