# Generated by Django 5.2.7 on 2025-10-17 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_rename_name_contestant_name_or_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestant',
            name='group_size',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contestant',
            name='is_group',
            field=models.BooleanField(default=False),
        ),
    ]
