# Generated by Django 5.2.7 on 2025-10-17 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0003_contestant_group_size_contestant_is_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contestant',
            name='submitted_at',
        ),
        migrations.AddField(
            model_name='contestant',
            name='video_submission',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
        migrations.AlterField(
            model_name='contestant',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
